# Generated by Django 5.2.17 on 2026-09-15 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(verbose_name='وضعیت و موارد قابل پیگیری')),
                ('equipment_status', models.CharField(blank=True, max_length=200, verbose_name='وضعیت تجهیزات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('incoming_guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_handovers', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cگیرنده')),
                ('outgoing_guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_handovers', to=settings.AUTH_USER_MODEL, verbose_name='تحویل\u200cدهنده')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
