# Generated by Django 5.2.17 on 2026-09-15 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'فرد'), ('vehicle', 'خودرو')], max_length=10, verbose_name='نوع')),
                ('direction', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج')], max_length=5, verbose_name='جهت')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام شخص / راننده')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('vehicle_plate', models.CharField(blank=True, max_length=30, verbose_name='پلاک خودرو')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='شرکت / مقصد')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
