# Generated by Django 5.2.17 on 2026-09-15 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام ایستگاه')),
                ('location_note', models.CharField(blank=True, max_length=200, verbose_name='محل')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.CreateModel(
            name='PatrolMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مأموریت')),
                ('starts_at', models.DateTimeField(verbose_name='شروع')),
                ('ends_at', models.DateTimeField(verbose_name='پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('missed', 'انجام نشده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoints', models.ManyToManyField(to='patrol.checkpoint', verbose_name='ایستگاه\u200cها')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='نگهبان')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان سرور')),
                ('photo', models.ImageField(blank=True, upload_to='patrol/', verbose_name='عکس زنده')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='یادداشت')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patrol.checkpoint')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='patrol.patrolmission')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mission', 'checkpoint')},
            },
        ),
    ]
