# Generated by Django 5.2.17 on 2026-09-15 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='عنوان واقعه')),
                ('description', models.TextField(verbose_name='شرح')),
                ('severity', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'فوری')], default='normal', max_length=10, verbose_name='اهمیت')),
                ('photo', models.ImageField(blank=True, upload_to='incidents/', verbose_name='عکس')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
